// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notes.Api.DbContexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Notes.Api.Migrations
{
    [DbContext(typeof(NotesContext))]
    partial class NotesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Notes.Api.Entities.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("90e92bd6-f222-43ca-a650-fd10a0717f24"),
                            NoteText = "A note by David",
                            OwnerId = "d860efca-22d9-47fd-8249-791ba61b07c7"
                        },
                        new
                        {
                            Id = new Guid("3358d2bd-9f30-4442-aa12-f673d23f2d8c"),
                            NoteText = "Another note by David",
                            OwnerId = "d860efca-22d9-47fd-8249-791ba61b07c7"
                        },
                        new
                        {
                            Id = new Guid("e1c4b0b2-302d-4286-b11b-695f6b68215e"),
                            NoteText = "A note by Emma",
                            OwnerId = "b7539694-97e7-4dfe-84da-b4256e1ff5c7"
                        },
                        new
                        {
                            Id = new Guid("db314a0e-3205-4c97-910b-01a99037f477"),
                            NoteText = "Another note by Emma",
                            OwnerId = "b7539694-97e7-4dfe-84da-b4256e1ff5c7"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
